replicaCount: 3

image:
  repository: postgres
  tag: "13.3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: true
  storageClass: "manual"
  accessModes:
    - ReadWriteOnce
  size: "5Gi"

postgresql:
  username: postgres
  password: password
  database: mydatabase

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
