replicaCount: 3

image:
  repository: alishazaei/patroni
  tag: "16.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 1432

persistence:
  enabled: true
  storageClass: manual
  accessModes: ReadWriteOnce
  size: "8Gi"
  claimsize: "1Gi"

postgresql:
  username: postgres
  password: password
  database: mydatabase
  data_mountpath: /var/lib/postgresql/data

nodeselector:
  key: "kubernetes.io/hostname"
  value: 
    - "vm3"
    - "vm4"

patroni:
  ttl: 30                        
  loop_wait: 10                    
  retry_timeout: 10            
  maximum_lag_on_failover: 1048576
  synchronous_mode: true

admin:
  username: postgres                      
  password: supersecretpassword           

replication:
  username: replicator                   
  password: replicationpassword           

rewind:
  username: rewind                          
  password: rewindpassword                  

backup:
  archiveMode: "on"                        
  archiveTimeout: 60                       
  schedule: "0 * * * *"

patroniPort: 8008 
postgresqlPort: 5432

parameters:
  shared_buffers: "256MB"                  
  max_worker_processes: 8

