apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "my-postgresql.fullname" . }}-pv
  labels:
    app.kubernetes.io/name: {{ include "my-postgresql.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
    - {{ .Values.persistence.accessModes }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  hostPath:
    path: /data/{{ include "my-postgresql.fullname" . }} 