apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "my-postgresql.fullname" . }}-pvc
  labels:
    app.kubernetes.io/name: {{ include "my-postgresql.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - {{ .Values.persistence.accessModes  }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
