apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: patroni-rolebinding
  namespace: default  # or your specific namespace
subjects:
  - kind: ServiceAccount
    name: patroni-sa
    namespace: default  
roleRef:
  kind: ClusterRole
  name: patroni-role
  apiGroup: rbac.authorization.k8s.io
