apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-postgresql.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "my-postgresql.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  postgresql-password: {{ .Values.postgresql.password | b64enc }}
