apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    app.kubernetes.io/name: 
    helm.sh/chart: postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  clusterIP: None 
  ports:
    - port: {{ .Values.service.port }}
      name: postgres
      targetPort: 5432
    - port: 8008
      name: patroni-api
      targetPort: 8008
  selector:
    app.kubernetes.io/name: {{ include "postgresql.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}