apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "postgresql.name" . }}
    helm.sh/chart: postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  serviceName: {{ include "postgresql.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "postgresql.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "postgresql.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PATRONI_KUBERNETES_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PATRONI_KUBERNETES_BYPASS_API_SERVICE
              value: 'true'
            - name: PATRONI_KUBERNETES_USE_ENDPOINTS
              value: 'true'
            - name: PATRONI_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PATRONI_KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: {{ .Values.service.port }}
              name: postgres
            - containerPort: 8008
              name: patroni-api
          volumeMounts:
            - name: postgresql-data
              mountPath: {{ .Values.postgresql.data_mountpath }}
              subPath: pgdata
            - name: config
              mountPath: /etc/patroni/patroni.yml
              subPath: patroni.yml
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "postgresql.fullname" . }} 
            
  volumeClaimTemplates:
    - metadata:
        name: postgresql-data
        labels:
          app.kubernetes.io/name: {{ include "postgresql.name" . }}
          app.kubernetes.io/instance: {{ .Release.Name }}
      spec:
        accessModes:  
          - {{ .Values.persistence.accessModes  }} 
        resources:
          requests:
            storage: {{ .Values.persistence.claimsize | quote }}
        storageClassName: os
        volumeMode: Filesystem

